// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/prompt.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

public interface CreatePromptEvaluationRunResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.server.v1.CreatePromptEvaluationRunResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chalk.server.v1.PromptEvaluationRun evaluation_run = 1 [json_name = "evaluationRun"];</code>
   * @return Whether the evaluationRun field is set.
   */
  boolean hasEvaluationRun();
  /**
   * <code>.chalk.server.v1.PromptEvaluationRun evaluation_run = 1 [json_name = "evaluationRun"];</code>
   * @return The evaluationRun.
   */
  ai.chalk.protos.chalk.server.v1.PromptEvaluationRun getEvaluationRun();
  /**
   * <code>.chalk.server.v1.PromptEvaluationRun evaluation_run = 1 [json_name = "evaluationRun"];</code>
   */
  ai.chalk.protos.chalk.server.v1.PromptEvaluationRunOrBuilder getEvaluationRunOrBuilder();
}
