// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/builder.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

/**
 * Protobuf type {@code chalk.server.v1.EnvoyGatewayAllowedRoutes}
 */
public final class EnvoyGatewayAllowedRoutes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chalk.server.v1.EnvoyGatewayAllowedRoutes)
    EnvoyGatewayAllowedRoutesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnvoyGatewayAllowedRoutes.newBuilder() to construct.
  private EnvoyGatewayAllowedRoutes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnvoyGatewayAllowedRoutes() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnvoyGatewayAllowedRoutes();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.chalk.protos.chalk.server.v1.BuilderProto.internal_static_chalk_server_v1_EnvoyGatewayAllowedRoutes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.chalk.protos.chalk.server.v1.BuilderProto.internal_static_chalk_server_v1_EnvoyGatewayAllowedRoutes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes.class, ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes.Builder.class);
  }

  private int bitField0_;
  public static final int NAMESPACES_FIELD_NUMBER = 1;
  private ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces_;
  /**
   * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
   * @return Whether the namespaces field is set.
   */
  @java.lang.Override
  public boolean hasNamespaces() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
   * @return The namespaces.
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces getNamespaces() {
    return namespaces_ == null ? ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.getDefaultInstance() : namespaces_;
  }
  /**
   * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespacesOrBuilder getNamespacesOrBuilder() {
    return namespaces_ == null ? ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.getDefaultInstance() : namespaces_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getNamespaces());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNamespaces());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes)) {
      return super.equals(obj);
    }
    ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes other = (ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes) obj;

    if (hasNamespaces() != other.hasNamespaces()) return false;
    if (hasNamespaces()) {
      if (!getNamespaces()
          .equals(other.getNamespaces())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNamespaces()) {
      hash = (37 * hash) + NAMESPACES_FIELD_NUMBER;
      hash = (53 * hash) + getNamespaces().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chalk.server.v1.EnvoyGatewayAllowedRoutes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chalk.server.v1.EnvoyGatewayAllowedRoutes)
      ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.chalk.protos.chalk.server.v1.BuilderProto.internal_static_chalk_server_v1_EnvoyGatewayAllowedRoutes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.chalk.protos.chalk.server.v1.BuilderProto.internal_static_chalk_server_v1_EnvoyGatewayAllowedRoutes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes.class, ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes.Builder.class);
    }

    // Construct using ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNamespacesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      namespaces_ = null;
      if (namespacesBuilder_ != null) {
        namespacesBuilder_.dispose();
        namespacesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.chalk.protos.chalk.server.v1.BuilderProto.internal_static_chalk_server_v1_EnvoyGatewayAllowedRoutes_descriptor;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes getDefaultInstanceForType() {
      return ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes.getDefaultInstance();
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes build() {
      ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes buildPartial() {
      ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes result = new ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.namespaces_ = namespacesBuilder_ == null
            ? namespaces_
            : namespacesBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes) {
        return mergeFrom((ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes other) {
      if (other == ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes.getDefaultInstance()) return this;
      if (other.hasNamespaces()) {
        mergeNamespaces(other.getNamespaces());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getNamespacesFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces, ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.Builder, ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespacesOrBuilder> namespacesBuilder_;
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     * @return Whether the namespaces field is set.
     */
    public boolean hasNamespaces() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     * @return The namespaces.
     */
    public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces getNamespaces() {
      if (namespacesBuilder_ == null) {
        return namespaces_ == null ? ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.getDefaultInstance() : namespaces_;
      } else {
        return namespacesBuilder_.getMessage();
      }
    }
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     */
    public Builder setNamespaces(ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces value) {
      if (namespacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        namespaces_ = value;
      } else {
        namespacesBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     */
    public Builder setNamespaces(
        ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.Builder builderForValue) {
      if (namespacesBuilder_ == null) {
        namespaces_ = builderForValue.build();
      } else {
        namespacesBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     */
    public Builder mergeNamespaces(ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces value) {
      if (namespacesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          namespaces_ != null &&
          namespaces_ != ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.getDefaultInstance()) {
          getNamespacesBuilder().mergeFrom(value);
        } else {
          namespaces_ = value;
        }
      } else {
        namespacesBuilder_.mergeFrom(value);
      }
      if (namespaces_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     */
    public Builder clearNamespaces() {
      bitField0_ = (bitField0_ & ~0x00000001);
      namespaces_ = null;
      if (namespacesBuilder_ != null) {
        namespacesBuilder_.dispose();
        namespacesBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     */
    public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.Builder getNamespacesBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getNamespacesFieldBuilder().getBuilder();
    }
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     */
    public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespacesOrBuilder getNamespacesOrBuilder() {
      if (namespacesBuilder_ != null) {
        return namespacesBuilder_.getMessageOrBuilder();
      } else {
        return namespaces_ == null ?
            ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.getDefaultInstance() : namespaces_;
      }
    }
    /**
     * <code>.chalk.server.v1.EnvoyGatewayAllowedNamespaces namespaces = 1 [json_name = "namespaces"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces, ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.Builder, ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespacesOrBuilder> 
        getNamespacesFieldBuilder() {
      if (namespacesBuilder_ == null) {
        namespacesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces, ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespaces.Builder, ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedNamespacesOrBuilder>(
                getNamespaces(),
                getParentForChildren(),
                isClean());
        namespaces_ = null;
      }
      return namespacesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chalk.server.v1.EnvoyGatewayAllowedRoutes)
  }

  // @@protoc_insertion_point(class_scope:chalk.server.v1.EnvoyGatewayAllowedRoutes)
  private static final ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes();
  }

  public static ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnvoyGatewayAllowedRoutes>
      PARSER = new com.google.protobuf.AbstractParser<EnvoyGatewayAllowedRoutes>() {
    @java.lang.Override
    public EnvoyGatewayAllowedRoutes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EnvoyGatewayAllowedRoutes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnvoyGatewayAllowedRoutes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.chalk.protos.chalk.server.v1.EnvoyGatewayAllowedRoutes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

