// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/environment.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

/**
 * Protobuf type {@code chalk.server.v1.GCPWorkloadIdentity}
 */
public final class GCPWorkloadIdentity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chalk.server.v1.GCPWorkloadIdentity)
    GCPWorkloadIdentityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GCPWorkloadIdentity.newBuilder() to construct.
  private GCPWorkloadIdentity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GCPWorkloadIdentity() {
    gcpProjectNumber_ = "";
    gcpServiceAccount_ = "";
    poolId_ = "";
    providerId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GCPWorkloadIdentity();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.chalk.protos.chalk.server.v1.EnvironmentProto.internal_static_chalk_server_v1_GCPWorkloadIdentity_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.chalk.protos.chalk.server.v1.EnvironmentProto.internal_static_chalk_server_v1_GCPWorkloadIdentity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity.class, ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity.Builder.class);
  }

  public static final int GCP_PROJECT_NUMBER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gcpProjectNumber_ = "";
  /**
   * <code>string gcp_project_number = 1 [json_name = "gcpProjectNumber"];</code>
   * @return The gcpProjectNumber.
   */
  @java.lang.Override
  public java.lang.String getGcpProjectNumber() {
    java.lang.Object ref = gcpProjectNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gcpProjectNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string gcp_project_number = 1 [json_name = "gcpProjectNumber"];</code>
   * @return The bytes for gcpProjectNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGcpProjectNumberBytes() {
    java.lang.Object ref = gcpProjectNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gcpProjectNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GCP_SERVICE_ACCOUNT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gcpServiceAccount_ = "";
  /**
   * <code>string gcp_service_account = 2 [json_name = "gcpServiceAccount"];</code>
   * @return The gcpServiceAccount.
   */
  @java.lang.Override
  public java.lang.String getGcpServiceAccount() {
    java.lang.Object ref = gcpServiceAccount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gcpServiceAccount_ = s;
      return s;
    }
  }
  /**
   * <code>string gcp_service_account = 2 [json_name = "gcpServiceAccount"];</code>
   * @return The bytes for gcpServiceAccount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGcpServiceAccountBytes() {
    java.lang.Object ref = gcpServiceAccount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gcpServiceAccount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POOL_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object poolId_ = "";
  /**
   * <code>string pool_id = 3 [json_name = "poolId"];</code>
   * @return The poolId.
   */
  @java.lang.Override
  public java.lang.String getPoolId() {
    java.lang.Object ref = poolId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      poolId_ = s;
      return s;
    }
  }
  /**
   * <code>string pool_id = 3 [json_name = "poolId"];</code>
   * @return The bytes for poolId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPoolIdBytes() {
    java.lang.Object ref = poolId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      poolId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVIDER_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object providerId_ = "";
  /**
   * <code>string provider_id = 4 [json_name = "providerId"];</code>
   * @return The providerId.
   */
  @java.lang.Override
  public java.lang.String getProviderId() {
    java.lang.Object ref = providerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      providerId_ = s;
      return s;
    }
  }
  /**
   * <code>string provider_id = 4 [json_name = "providerId"];</code>
   * @return The bytes for providerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProviderIdBytes() {
    java.lang.Object ref = providerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      providerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gcpProjectNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, gcpProjectNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gcpServiceAccount_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gcpServiceAccount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(poolId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, poolId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(providerId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, providerId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gcpProjectNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, gcpProjectNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gcpServiceAccount_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gcpServiceAccount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(poolId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, poolId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(providerId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, providerId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity)) {
      return super.equals(obj);
    }
    ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity other = (ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity) obj;

    if (!getGcpProjectNumber()
        .equals(other.getGcpProjectNumber())) return false;
    if (!getGcpServiceAccount()
        .equals(other.getGcpServiceAccount())) return false;
    if (!getPoolId()
        .equals(other.getPoolId())) return false;
    if (!getProviderId()
        .equals(other.getProviderId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GCP_PROJECT_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getGcpProjectNumber().hashCode();
    hash = (37 * hash) + GCP_SERVICE_ACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getGcpServiceAccount().hashCode();
    hash = (37 * hash) + POOL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPoolId().hashCode();
    hash = (37 * hash) + PROVIDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getProviderId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chalk.server.v1.GCPWorkloadIdentity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chalk.server.v1.GCPWorkloadIdentity)
      ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.chalk.protos.chalk.server.v1.EnvironmentProto.internal_static_chalk_server_v1_GCPWorkloadIdentity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.chalk.protos.chalk.server.v1.EnvironmentProto.internal_static_chalk_server_v1_GCPWorkloadIdentity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity.class, ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity.Builder.class);
    }

    // Construct using ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      gcpProjectNumber_ = "";
      gcpServiceAccount_ = "";
      poolId_ = "";
      providerId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.chalk.protos.chalk.server.v1.EnvironmentProto.internal_static_chalk_server_v1_GCPWorkloadIdentity_descriptor;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity getDefaultInstanceForType() {
      return ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity.getDefaultInstance();
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity build() {
      ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity buildPartial() {
      ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity result = new ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.gcpProjectNumber_ = gcpProjectNumber_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gcpServiceAccount_ = gcpServiceAccount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.poolId_ = poolId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.providerId_ = providerId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity) {
        return mergeFrom((ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity other) {
      if (other == ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity.getDefaultInstance()) return this;
      if (!other.getGcpProjectNumber().isEmpty()) {
        gcpProjectNumber_ = other.gcpProjectNumber_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getGcpServiceAccount().isEmpty()) {
        gcpServiceAccount_ = other.gcpServiceAccount_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPoolId().isEmpty()) {
        poolId_ = other.poolId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getProviderId().isEmpty()) {
        providerId_ = other.providerId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              gcpProjectNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              gcpServiceAccount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              poolId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              providerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object gcpProjectNumber_ = "";
    /**
     * <code>string gcp_project_number = 1 [json_name = "gcpProjectNumber"];</code>
     * @return The gcpProjectNumber.
     */
    public java.lang.String getGcpProjectNumber() {
      java.lang.Object ref = gcpProjectNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gcpProjectNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gcp_project_number = 1 [json_name = "gcpProjectNumber"];</code>
     * @return The bytes for gcpProjectNumber.
     */
    public com.google.protobuf.ByteString
        getGcpProjectNumberBytes() {
      java.lang.Object ref = gcpProjectNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gcpProjectNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gcp_project_number = 1 [json_name = "gcpProjectNumber"];</code>
     * @param value The gcpProjectNumber to set.
     * @return This builder for chaining.
     */
    public Builder setGcpProjectNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gcpProjectNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string gcp_project_number = 1 [json_name = "gcpProjectNumber"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGcpProjectNumber() {
      gcpProjectNumber_ = getDefaultInstance().getGcpProjectNumber();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string gcp_project_number = 1 [json_name = "gcpProjectNumber"];</code>
     * @param value The bytes for gcpProjectNumber to set.
     * @return This builder for chaining.
     */
    public Builder setGcpProjectNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gcpProjectNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object gcpServiceAccount_ = "";
    /**
     * <code>string gcp_service_account = 2 [json_name = "gcpServiceAccount"];</code>
     * @return The gcpServiceAccount.
     */
    public java.lang.String getGcpServiceAccount() {
      java.lang.Object ref = gcpServiceAccount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gcpServiceAccount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gcp_service_account = 2 [json_name = "gcpServiceAccount"];</code>
     * @return The bytes for gcpServiceAccount.
     */
    public com.google.protobuf.ByteString
        getGcpServiceAccountBytes() {
      java.lang.Object ref = gcpServiceAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gcpServiceAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gcp_service_account = 2 [json_name = "gcpServiceAccount"];</code>
     * @param value The gcpServiceAccount to set.
     * @return This builder for chaining.
     */
    public Builder setGcpServiceAccount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gcpServiceAccount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string gcp_service_account = 2 [json_name = "gcpServiceAccount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearGcpServiceAccount() {
      gcpServiceAccount_ = getDefaultInstance().getGcpServiceAccount();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string gcp_service_account = 2 [json_name = "gcpServiceAccount"];</code>
     * @param value The bytes for gcpServiceAccount to set.
     * @return This builder for chaining.
     */
    public Builder setGcpServiceAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      gcpServiceAccount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object poolId_ = "";
    /**
     * <code>string pool_id = 3 [json_name = "poolId"];</code>
     * @return The poolId.
     */
    public java.lang.String getPoolId() {
      java.lang.Object ref = poolId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        poolId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pool_id = 3 [json_name = "poolId"];</code>
     * @return The bytes for poolId.
     */
    public com.google.protobuf.ByteString
        getPoolIdBytes() {
      java.lang.Object ref = poolId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        poolId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pool_id = 3 [json_name = "poolId"];</code>
     * @param value The poolId to set.
     * @return This builder for chaining.
     */
    public Builder setPoolId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      poolId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string pool_id = 3 [json_name = "poolId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPoolId() {
      poolId_ = getDefaultInstance().getPoolId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string pool_id = 3 [json_name = "poolId"];</code>
     * @param value The bytes for poolId to set.
     * @return This builder for chaining.
     */
    public Builder setPoolIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      poolId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object providerId_ = "";
    /**
     * <code>string provider_id = 4 [json_name = "providerId"];</code>
     * @return The providerId.
     */
    public java.lang.String getProviderId() {
      java.lang.Object ref = providerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        providerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string provider_id = 4 [json_name = "providerId"];</code>
     * @return The bytes for providerId.
     */
    public com.google.protobuf.ByteString
        getProviderIdBytes() {
      java.lang.Object ref = providerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        providerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string provider_id = 4 [json_name = "providerId"];</code>
     * @param value The providerId to set.
     * @return This builder for chaining.
     */
    public Builder setProviderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      providerId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string provider_id = 4 [json_name = "providerId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProviderId() {
      providerId_ = getDefaultInstance().getProviderId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string provider_id = 4 [json_name = "providerId"];</code>
     * @param value The bytes for providerId to set.
     * @return This builder for chaining.
     */
    public Builder setProviderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      providerId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chalk.server.v1.GCPWorkloadIdentity)
  }

  // @@protoc_insertion_point(class_scope:chalk.server.v1.GCPWorkloadIdentity)
  private static final ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity();
  }

  public static ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GCPWorkloadIdentity>
      PARSER = new com.google.protobuf.AbstractParser<GCPWorkloadIdentity>() {
    @java.lang.Override
    public GCPWorkloadIdentity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GCPWorkloadIdentity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GCPWorkloadIdentity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.chalk.protos.chalk.server.v1.GCPWorkloadIdentity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

