// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/named_query.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

public interface GetAllNamedQueriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.server.v1.GetAllNamedQueriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .chalk.graph.v1.NamedQuery named_queries = 1 [json_name = "namedQueries"];</code>
   */
  java.util.List<ai.chalk.protos.chalk.graph.v1.NamedQuery> 
      getNamedQueriesList();
  /**
   * <code>repeated .chalk.graph.v1.NamedQuery named_queries = 1 [json_name = "namedQueries"];</code>
   */
  ai.chalk.protos.chalk.graph.v1.NamedQuery getNamedQueries(int index);
  /**
   * <code>repeated .chalk.graph.v1.NamedQuery named_queries = 1 [json_name = "namedQueries"];</code>
   */
  int getNamedQueriesCount();
  /**
   * <code>repeated .chalk.graph.v1.NamedQuery named_queries = 1 [json_name = "namedQueries"];</code>
   */
  java.util.List<? extends ai.chalk.protos.chalk.graph.v1.NamedQueryOrBuilder> 
      getNamedQueriesOrBuilderList();
  /**
   * <code>repeated .chalk.graph.v1.NamedQuery named_queries = 1 [json_name = "namedQueries"];</code>
   */
  ai.chalk.protos.chalk.graph.v1.NamedQueryOrBuilder getNamedQueriesOrBuilder(
      int index);
}
