// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/manager.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

public interface GetClusterEnvironmentsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.server.v1.GetClusterEnvironmentsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string environment_ids = 1 [json_name = "environmentIds"];</code>
   * @return A list containing the environmentIds.
   */
  java.util.List<java.lang.String>
      getEnvironmentIdsList();
  /**
   * <code>repeated string environment_ids = 1 [json_name = "environmentIds"];</code>
   * @return The count of environmentIds.
   */
  int getEnvironmentIdsCount();
  /**
   * <code>repeated string environment_ids = 1 [json_name = "environmentIds"];</code>
   * @param index The index of the element to return.
   * @return The environmentIds at the given index.
   */
  java.lang.String getEnvironmentIds(int index);
  /**
   * <code>repeated string environment_ids = 1 [json_name = "environmentIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the environmentIds at the given index.
   */
  com.google.protobuf.ByteString
      getEnvironmentIdsBytes(int index);
}
