// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/kube.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

public interface GetKubernetesPersistentVolumesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.server.v1.GetKubernetesPersistentVolumesRequest)
    com.google.protobuf.MessageOrBuilder {
}
