// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/billing.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

public interface GetNodesAndPodsUIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.server.v1.GetNodesAndPodsUIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesNodeData nodes = 1 [json_name = "nodes"];</code>
   */
  java.util.List<ai.chalk.protos.chalk.kubernetes.v1.KubernetesNodeData> 
      getNodesList();
  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesNodeData nodes = 1 [json_name = "nodes"];</code>
   */
  ai.chalk.protos.chalk.kubernetes.v1.KubernetesNodeData getNodes(int index);
  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesNodeData nodes = 1 [json_name = "nodes"];</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesNodeData nodes = 1 [json_name = "nodes"];</code>
   */
  java.util.List<? extends ai.chalk.protos.chalk.kubernetes.v1.KubernetesNodeDataOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesNodeData nodes = 1 [json_name = "nodes"];</code>
   */
  ai.chalk.protos.chalk.kubernetes.v1.KubernetesNodeDataOrBuilder getNodesOrBuilder(
      int index);

  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesPodData pods = 2 [json_name = "pods"];</code>
   */
  java.util.List<ai.chalk.protos.chalk.kubernetes.v1.KubernetesPodData> 
      getPodsList();
  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesPodData pods = 2 [json_name = "pods"];</code>
   */
  ai.chalk.protos.chalk.kubernetes.v1.KubernetesPodData getPods(int index);
  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesPodData pods = 2 [json_name = "pods"];</code>
   */
  int getPodsCount();
  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesPodData pods = 2 [json_name = "pods"];</code>
   */
  java.util.List<? extends ai.chalk.protos.chalk.kubernetes.v1.KubernetesPodDataOrBuilder> 
      getPodsOrBuilderList();
  /**
   * <code>repeated .chalk.kubernetes.v1.KubernetesPodData pods = 2 [json_name = "pods"];</code>
   */
  ai.chalk.protos.chalk.kubernetes.v1.KubernetesPodDataOrBuilder getPodsOrBuilder(
      int index);
}
