// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/link.proto

// Protobuf Java Version: 3.25.3
package ai.chalk.protos.chalk.server.v1;

public final class LinkProto {
  private LinkProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_LinkToken_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_LinkToken_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_GetLinkSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_GetLinkSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_GetLinkSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_GetLinkSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_CreateLinkSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_CreateLinkSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_CreateLinkSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_CreateLinkSessionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032chalk/server/v1/link.proto\022\017chalk.serv" +
      "er.v1\032\037google/protobuf/timestamp.proto\"\210" +
      "\002\n\tLinkToken\022\022\n\004name\030\001 \001(\tR\004name\022\033\n\tclie" +
      "nt_id\030\002 \001(\tR\010clientId\022#\n\rclient_secret\030\003" +
      " \001(\tR\014clientSecret\022\035\n\napi_server\030\004 \001(\tR\t" +
      "apiServer\0222\n\022active_environment\030\005 \001(\tH\000R" +
      "\021activeEnvironment\210\001\001\022;\n\013valid_until\030\006 \001" +
      "(\0132\032.google.protobuf.TimestampR\nvalidUnt" +
      "ilB\025\n\023_active_environment\"W\n\025GetLinkSess" +
      "ionRequest\022\033\n\tlink_code\030\001 \001(\tR\010linkCode\022" +
      "!\n\014project_name\030\002 \001(\tR\013projectName\"\257\001\n\026G" +
      "etLinkSessionResponse\022:\n\006status\030\001 \001(\0162\"." +
      "chalk.server.v1.LinkSessionStatusR\006statu" +
      "s\022\030\n\007message\030\002 \001(\tR\007message\0225\n\005token\030\003 \001" +
      "(\0132\032.chalk.server.v1.LinkTokenH\000R\005token\210" +
      "\001\001B\010\n\006_token\"\032\n\030CreateLinkSessionRequest" +
      "\"\220\001\n\031CreateLinkSessionResponse\022\033\n\tlink_c" +
      "ode\030\001 \001(\tR\010linkCode\022\033\n\tauth_link\030\002 \001(\tR\010" +
      "authLink\0229\n\nexpires_at\030\003 \001(\0132\032.google.pr" +
      "otobuf.TimestampR\texpiresAt*\340\001\n\021LinkSess" +
      "ionStatus\022#\n\037LINK_SESSION_STATUS_UNSPECI" +
      "FIED\020\000\022\037\n\033LINK_SESSION_STATUS_PENDING\020\001\022" +
      "\037\n\033LINK_SESSION_STATUS_SUCCESS\020\002\022\036\n\032LINK" +
      "_SESSION_STATUS_FAILED\020\003\022!\n\035LINK_SESSION" +
      "_STATUS_NOT_FOUND\020\004\022!\n\035LINK_SESSION_STAT" +
      "US_FORBIDDEN\020\005B\236\001\n\037ai.chalk.protos.chalk" +
      ".server.v1B\tLinkProtoP\001Z\022server/v1;serve" +
      "rv1\242\002\003CSX\252\002\017Chalk.Server.V1\312\002\017Chalk\\Serv" +
      "er\\V1\342\002\033Chalk\\Server\\V1\\GPBMetadata\352\002\021Ch" +
      "alk::Server::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_chalk_server_v1_LinkToken_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chalk_server_v1_LinkToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_LinkToken_descriptor,
        new java.lang.String[] { "Name", "ClientId", "ClientSecret", "ApiServer", "ActiveEnvironment", "ValidUntil", });
    internal_static_chalk_server_v1_GetLinkSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chalk_server_v1_GetLinkSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_GetLinkSessionRequest_descriptor,
        new java.lang.String[] { "LinkCode", "ProjectName", });
    internal_static_chalk_server_v1_GetLinkSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chalk_server_v1_GetLinkSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_GetLinkSessionResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Token", });
    internal_static_chalk_server_v1_CreateLinkSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chalk_server_v1_CreateLinkSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_CreateLinkSessionRequest_descriptor,
        new java.lang.String[] { });
    internal_static_chalk_server_v1_CreateLinkSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_chalk_server_v1_CreateLinkSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_CreateLinkSessionResponse_descriptor,
        new java.lang.String[] { "LinkCode", "AuthLink", "ExpiresAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
