// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/team.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

/**
 * Protobuf type {@code chalk.server.v1.ListTeamInvitesResponse}
 */
public final class ListTeamInvitesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chalk.server.v1.ListTeamInvitesResponse)
    ListTeamInvitesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListTeamInvitesResponse.newBuilder() to construct.
  private ListTeamInvitesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListTeamInvitesResponse() {
    invites_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListTeamInvitesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.chalk.protos.chalk.server.v1.TeamProto.internal_static_chalk_server_v1_ListTeamInvitesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.chalk.protos.chalk.server.v1.TeamProto.internal_static_chalk_server_v1_ListTeamInvitesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse.class, ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse.Builder.class);
  }

  public static final int INVITES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<ai.chalk.protos.chalk.server.v1.TeamInvite> invites_;
  /**
   * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
   */
  @java.lang.Override
  public java.util.List<ai.chalk.protos.chalk.server.v1.TeamInvite> getInvitesList() {
    return invites_;
  }
  /**
   * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends ai.chalk.protos.chalk.server.v1.TeamInviteOrBuilder> 
      getInvitesOrBuilderList() {
    return invites_;
  }
  /**
   * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
   */
  @java.lang.Override
  public int getInvitesCount() {
    return invites_.size();
  }
  /**
   * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.server.v1.TeamInvite getInvites(int index) {
    return invites_.get(index);
  }
  /**
   * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.server.v1.TeamInviteOrBuilder getInvitesOrBuilder(
      int index) {
    return invites_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < invites_.size(); i++) {
      output.writeMessage(1, invites_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < invites_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, invites_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse)) {
      return super.equals(obj);
    }
    ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse other = (ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse) obj;

    if (!getInvitesList()
        .equals(other.getInvitesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInvitesCount() > 0) {
      hash = (37 * hash) + INVITES_FIELD_NUMBER;
      hash = (53 * hash) + getInvitesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chalk.server.v1.ListTeamInvitesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chalk.server.v1.ListTeamInvitesResponse)
      ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.chalk.protos.chalk.server.v1.TeamProto.internal_static_chalk_server_v1_ListTeamInvitesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.chalk.protos.chalk.server.v1.TeamProto.internal_static_chalk_server_v1_ListTeamInvitesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse.class, ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse.Builder.class);
    }

    // Construct using ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (invitesBuilder_ == null) {
        invites_ = java.util.Collections.emptyList();
      } else {
        invites_ = null;
        invitesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.chalk.protos.chalk.server.v1.TeamProto.internal_static_chalk_server_v1_ListTeamInvitesResponse_descriptor;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse getDefaultInstanceForType() {
      return ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse build() {
      ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse buildPartial() {
      ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse result = new ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse result) {
      if (invitesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          invites_ = java.util.Collections.unmodifiableList(invites_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.invites_ = invites_;
      } else {
        result.invites_ = invitesBuilder_.build();
      }
    }

    private void buildPartial0(ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse) {
        return mergeFrom((ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse other) {
      if (other == ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse.getDefaultInstance()) return this;
      if (invitesBuilder_ == null) {
        if (!other.invites_.isEmpty()) {
          if (invites_.isEmpty()) {
            invites_ = other.invites_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInvitesIsMutable();
            invites_.addAll(other.invites_);
          }
          onChanged();
        }
      } else {
        if (!other.invites_.isEmpty()) {
          if (invitesBuilder_.isEmpty()) {
            invitesBuilder_.dispose();
            invitesBuilder_ = null;
            invites_ = other.invites_;
            bitField0_ = (bitField0_ & ~0x00000001);
            invitesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvitesFieldBuilder() : null;
          } else {
            invitesBuilder_.addAllMessages(other.invites_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ai.chalk.protos.chalk.server.v1.TeamInvite m =
                  input.readMessage(
                      ai.chalk.protos.chalk.server.v1.TeamInvite.parser(),
                      extensionRegistry);
              if (invitesBuilder_ == null) {
                ensureInvitesIsMutable();
                invites_.add(m);
              } else {
                invitesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ai.chalk.protos.chalk.server.v1.TeamInvite> invites_ =
      java.util.Collections.emptyList();
    private void ensureInvitesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        invites_ = new java.util.ArrayList<ai.chalk.protos.chalk.server.v1.TeamInvite>(invites_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.chalk.protos.chalk.server.v1.TeamInvite, ai.chalk.protos.chalk.server.v1.TeamInvite.Builder, ai.chalk.protos.chalk.server.v1.TeamInviteOrBuilder> invitesBuilder_;

    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public java.util.List<ai.chalk.protos.chalk.server.v1.TeamInvite> getInvitesList() {
      if (invitesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invites_);
      } else {
        return invitesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public int getInvitesCount() {
      if (invitesBuilder_ == null) {
        return invites_.size();
      } else {
        return invitesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public ai.chalk.protos.chalk.server.v1.TeamInvite getInvites(int index) {
      if (invitesBuilder_ == null) {
        return invites_.get(index);
      } else {
        return invitesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder setInvites(
        int index, ai.chalk.protos.chalk.server.v1.TeamInvite value) {
      if (invitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitesIsMutable();
        invites_.set(index, value);
        onChanged();
      } else {
        invitesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder setInvites(
        int index, ai.chalk.protos.chalk.server.v1.TeamInvite.Builder builderForValue) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        invites_.set(index, builderForValue.build());
        onChanged();
      } else {
        invitesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder addInvites(ai.chalk.protos.chalk.server.v1.TeamInvite value) {
      if (invitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitesIsMutable();
        invites_.add(value);
        onChanged();
      } else {
        invitesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder addInvites(
        int index, ai.chalk.protos.chalk.server.v1.TeamInvite value) {
      if (invitesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvitesIsMutable();
        invites_.add(index, value);
        onChanged();
      } else {
        invitesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder addInvites(
        ai.chalk.protos.chalk.server.v1.TeamInvite.Builder builderForValue) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        invites_.add(builderForValue.build());
        onChanged();
      } else {
        invitesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder addInvites(
        int index, ai.chalk.protos.chalk.server.v1.TeamInvite.Builder builderForValue) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        invites_.add(index, builderForValue.build());
        onChanged();
      } else {
        invitesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder addAllInvites(
        java.lang.Iterable<? extends ai.chalk.protos.chalk.server.v1.TeamInvite> values) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invites_);
        onChanged();
      } else {
        invitesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder clearInvites() {
      if (invitesBuilder_ == null) {
        invites_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        invitesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public Builder removeInvites(int index) {
      if (invitesBuilder_ == null) {
        ensureInvitesIsMutable();
        invites_.remove(index);
        onChanged();
      } else {
        invitesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public ai.chalk.protos.chalk.server.v1.TeamInvite.Builder getInvitesBuilder(
        int index) {
      return getInvitesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public ai.chalk.protos.chalk.server.v1.TeamInviteOrBuilder getInvitesOrBuilder(
        int index) {
      if (invitesBuilder_ == null) {
        return invites_.get(index);  } else {
        return invitesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public java.util.List<? extends ai.chalk.protos.chalk.server.v1.TeamInviteOrBuilder> 
         getInvitesOrBuilderList() {
      if (invitesBuilder_ != null) {
        return invitesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invites_);
      }
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public ai.chalk.protos.chalk.server.v1.TeamInvite.Builder addInvitesBuilder() {
      return getInvitesFieldBuilder().addBuilder(
          ai.chalk.protos.chalk.server.v1.TeamInvite.getDefaultInstance());
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public ai.chalk.protos.chalk.server.v1.TeamInvite.Builder addInvitesBuilder(
        int index) {
      return getInvitesFieldBuilder().addBuilder(
          index, ai.chalk.protos.chalk.server.v1.TeamInvite.getDefaultInstance());
    }
    /**
     * <code>repeated .chalk.server.v1.TeamInvite invites = 1 [json_name = "invites"];</code>
     */
    public java.util.List<ai.chalk.protos.chalk.server.v1.TeamInvite.Builder> 
         getInvitesBuilderList() {
      return getInvitesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.chalk.protos.chalk.server.v1.TeamInvite, ai.chalk.protos.chalk.server.v1.TeamInvite.Builder, ai.chalk.protos.chalk.server.v1.TeamInviteOrBuilder> 
        getInvitesFieldBuilder() {
      if (invitesBuilder_ == null) {
        invitesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ai.chalk.protos.chalk.server.v1.TeamInvite, ai.chalk.protos.chalk.server.v1.TeamInvite.Builder, ai.chalk.protos.chalk.server.v1.TeamInviteOrBuilder>(
                invites_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        invites_ = null;
      }
      return invitesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chalk.server.v1.ListTeamInvitesResponse)
  }

  // @@protoc_insertion_point(class_scope:chalk.server.v1.ListTeamInvitesResponse)
  private static final ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse();
  }

  public static ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListTeamInvitesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListTeamInvitesResponse>() {
    @java.lang.Override
    public ListTeamInvitesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListTeamInvitesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListTeamInvitesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.chalk.protos.chalk.server.v1.ListTeamInvitesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

