// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/prompt.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

public interface ListPromptEvaluationRunsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.server.v1.ListPromptEvaluationRunsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string cursor = 1 [json_name = "cursor"];</code>
   * @return Whether the cursor field is set.
   */
  boolean hasCursor();
  /**
   * <code>optional string cursor = 1 [json_name = "cursor"];</code>
   * @return The cursor.
   */
  java.lang.String getCursor();
  /**
   * <code>optional string cursor = 1 [json_name = "cursor"];</code>
   * @return The bytes for cursor.
   */
  com.google.protobuf.ByteString
      getCursorBytes();

  /**
   * <code>optional int32 limit = 2 [json_name = "limit"];</code>
   * @return Whether the limit field is set.
   */
  boolean hasLimit();
  /**
   * <code>optional int32 limit = 2 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>optional string named_prompt_id = 3 [json_name = "namedPromptId"];</code>
   * @return Whether the namedPromptId field is set.
   */
  boolean hasNamedPromptId();
  /**
   * <code>optional string named_prompt_id = 3 [json_name = "namedPromptId"];</code>
   * @return The namedPromptId.
   */
  java.lang.String getNamedPromptId();
  /**
   * <code>optional string named_prompt_id = 3 [json_name = "namedPromptId"];</code>
   * @return The bytes for namedPromptId.
   */
  com.google.protobuf.ByteString
      getNamedPromptIdBytes();
}
