// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/pod_request.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

/**
 * Protobuf enum {@code chalk.server.v1.PodRequestResourceType}
 */
public enum PodRequestResourceType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>POD_REQUEST_RESOURCE_TYPE_UNSPECIFIED = 0;</code>
   */
  POD_REQUEST_RESOURCE_TYPE_UNSPECIFIED(0),
  /**
   * <code>POD_REQUEST_RESOURCE_TYPE_CPU = 1;</code>
   */
  POD_REQUEST_RESOURCE_TYPE_CPU(1),
  /**
   * <code>POD_REQUEST_RESOURCE_TYPE_MEMORY = 2;</code>
   */
  POD_REQUEST_RESOURCE_TYPE_MEMORY(2),
  /**
   * <code>POD_REQUEST_RESOURCE_TYPE_EPHEMERAL_STORAGE = 3;</code>
   */
  POD_REQUEST_RESOURCE_TYPE_EPHEMERAL_STORAGE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>POD_REQUEST_RESOURCE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int POD_REQUEST_RESOURCE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>POD_REQUEST_RESOURCE_TYPE_CPU = 1;</code>
   */
  public static final int POD_REQUEST_RESOURCE_TYPE_CPU_VALUE = 1;
  /**
   * <code>POD_REQUEST_RESOURCE_TYPE_MEMORY = 2;</code>
   */
  public static final int POD_REQUEST_RESOURCE_TYPE_MEMORY_VALUE = 2;
  /**
   * <code>POD_REQUEST_RESOURCE_TYPE_EPHEMERAL_STORAGE = 3;</code>
   */
  public static final int POD_REQUEST_RESOURCE_TYPE_EPHEMERAL_STORAGE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PodRequestResourceType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PodRequestResourceType forNumber(int value) {
    switch (value) {
      case 0: return POD_REQUEST_RESOURCE_TYPE_UNSPECIFIED;
      case 1: return POD_REQUEST_RESOURCE_TYPE_CPU;
      case 2: return POD_REQUEST_RESOURCE_TYPE_MEMORY;
      case 3: return POD_REQUEST_RESOURCE_TYPE_EPHEMERAL_STORAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PodRequestResourceType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PodRequestResourceType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PodRequestResourceType>() {
          public PodRequestResourceType findValueByNumber(int number) {
            return PodRequestResourceType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ai.chalk.protos.chalk.server.v1.PodRequestProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final PodRequestResourceType[] VALUES = values();

  public static PodRequestResourceType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PodRequestResourceType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:chalk.server.v1.PodRequestResourceType)
}

