// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/server/v1/webhook.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.server.v1;

public final class WebhookProto {
  private WebhookProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_Webhook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_Webhook_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_CreateWebhookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_CreateWebhookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_CreateWebhookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_CreateWebhookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_UpdateWebhookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_UpdateWebhookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_UpdateWebhookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_UpdateWebhookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_DeleteWebhookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_DeleteWebhookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_DeleteWebhookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_DeleteWebhookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_GetWebhookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_GetWebhookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_GetWebhookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_GetWebhookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_ListWebhooksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_ListWebhooksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chalk_server_v1_ListWebhooksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chalk_server_v1_ListWebhooksResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035chalk/server/v1/webhook.proto\022\017chalk.s" +
      "erver.v1\032\037chalk/auth/v1/permissions.prot" +
      "o\032\034google/protobuf/struct.proto\032\037google/" +
      "protobuf/timestamp.proto\"\207\003\n\007Webhook\022\016\n\002" +
      "id\030\001 \001(\tR\002id\022%\n\016environment_id\030\002 \001(\tR\ren" +
      "vironmentId\022\027\n\007team_id\030\003 \001(\tR\006teamId\022\022\n\004" +
      "name\030\004 \001(\tR\004name\022\020\n\003url\030\005 \001(\tR\003url\022$\n\rsu" +
      "bscriptions\030\006 \003(\tR\rsubscriptions\022\033\n\006secr" +
      "et\030\007 \001(\tH\000R\006secret\210\001\001\0226\n\007headers\030\010 \001(\0132\027" +
      ".google.protobuf.StructH\001R\007headers\210\001\001\0229\n" +
      "\ncreated_at\030\t \001(\0132\032.google.protobuf.Time" +
      "stampR\tcreatedAt\0229\n\nupdated_at\030\n \001(\0132\032.g" +
      "oogle.protobuf.TimestampR\tupdatedAtB\t\n\007_" +
      "secretB\n\n\010_headers\"\365\001\n\024CreateWebhookRequ" +
      "est\022%\n\016environment_id\030\001 \001(\tR\renvironment" +
      "Id\022\022\n\004name\030\002 \001(\tR\004name\022\020\n\003url\030\003 \001(\tR\003url" +
      "\022$\n\rsubscriptions\030\004 \003(\tR\rsubscriptions\022\033" +
      "\n\006secret\030\005 \001(\tH\000R\006secret\210\001\001\0226\n\007headers\030\006" +
      " \001(\0132\027.google.protobuf.StructH\001R\007headers" +
      "\210\001\001B\t\n\007_secretB\n\n\010_headers\"K\n\025CreateWebh" +
      "ookResponse\0222\n\007webhook\030\001 \001(\0132\030.chalk.ser" +
      "ver.v1.WebhookR\007webhook\"\371\001\n\024UpdateWebhoo" +
      "kRequest\022\016\n\002id\030\001 \001(\tR\002id\022\027\n\004name\030\002 \001(\tH\000" +
      "R\004name\210\001\001\022\025\n\003url\030\003 \001(\tH\001R\003url\210\001\001\022$\n\rsubs" +
      "criptions\030\004 \003(\tR\rsubscriptions\022\033\n\006secret" +
      "\030\005 \001(\tH\002R\006secret\210\001\001\0226\n\007headers\030\006 \001(\0132\027.g" +
      "oogle.protobuf.StructH\003R\007headers\210\001\001B\007\n\005_" +
      "nameB\006\n\004_urlB\t\n\007_secretB\n\n\010_headers\"K\n\025U" +
      "pdateWebhookResponse\0222\n\007webhook\030\001 \001(\0132\030." +
      "chalk.server.v1.WebhookR\007webhook\"&\n\024Dele" +
      "teWebhookRequest\022\016\n\002id\030\001 \001(\tR\002id\"K\n\025Dele" +
      "teWebhookResponse\0222\n\007webhook\030\001 \001(\0132\030.cha" +
      "lk.server.v1.WebhookR\007webhook\"#\n\021GetWebh" +
      "ookRequest\022\016\n\002id\030\001 \001(\tR\002id\"H\n\022GetWebhook" +
      "Response\0222\n\007webhook\030\001 \001(\0132\030.chalk.server" +
      ".v1.WebhookR\007webhook\"<\n\023ListWebhooksRequ" +
      "est\022%\n\016environment_id\030\001 \001(\tR\renvironment" +
      "Id\"L\n\024ListWebhooksResponse\0224\n\010webhooks\030\001" +
      " \003(\0132\030.chalk.server.v1.WebhookR\010webhooks" +
      "2\203\004\n\016WebhookService\022c\n\rCreateWebhook\022%.c" +
      "halk.server.v1.CreateWebhookRequest\032&.ch" +
      "alk.server.v1.CreateWebhookResponse\"\003\200}\005" +
      "\022c\n\rUpdateWebhook\022%.chalk.server.v1.Upda" +
      "teWebhookRequest\032&.chalk.server.v1.Updat" +
      "eWebhookResponse\"\003\200}\005\022c\n\rDeleteWebhook\022%" +
      ".chalk.server.v1.DeleteWebhookRequest\032&." +
      "chalk.server.v1.DeleteWebhookResponse\"\003\200" +
      "}\005\022]\n\nGetWebhook\022\".chalk.server.v1.GetWe" +
      "bhookRequest\032#.chalk.server.v1.GetWebhoo" +
      "kResponse\"\006\220\002\001\200}\006\022c\n\014ListWebhooks\022$.chal" +
      "k.server.v1.ListWebhooksRequest\032%.chalk." +
      "server.v1.ListWebhooksResponse\"\006\220\002\001\200}\006B\241" +
      "\001\n\037ai.chalk.protos.chalk.server.v1B\014Webh" +
      "ookProtoP\001Z\022server/v1;serverv1\242\002\003CSX\252\002\017C" +
      "halk.Server.V1\312\002\017Chalk\\Server\\V1\342\002\033Chalk" +
      "\\Server\\V1\\GPBMetadata\352\002\021Chalk::Server::" +
      "V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ai.chalk.protos.chalk.auth.v1.PermissionsProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_chalk_server_v1_Webhook_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chalk_server_v1_Webhook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_Webhook_descriptor,
        new java.lang.String[] { "Id", "EnvironmentId", "TeamId", "Name", "Url", "Subscriptions", "Secret", "Headers", "CreatedAt", "UpdatedAt", });
    internal_static_chalk_server_v1_CreateWebhookRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chalk_server_v1_CreateWebhookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_CreateWebhookRequest_descriptor,
        new java.lang.String[] { "EnvironmentId", "Name", "Url", "Subscriptions", "Secret", "Headers", });
    internal_static_chalk_server_v1_CreateWebhookResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chalk_server_v1_CreateWebhookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_CreateWebhookResponse_descriptor,
        new java.lang.String[] { "Webhook", });
    internal_static_chalk_server_v1_UpdateWebhookRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chalk_server_v1_UpdateWebhookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_UpdateWebhookRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Url", "Subscriptions", "Secret", "Headers", });
    internal_static_chalk_server_v1_UpdateWebhookResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_chalk_server_v1_UpdateWebhookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_UpdateWebhookResponse_descriptor,
        new java.lang.String[] { "Webhook", });
    internal_static_chalk_server_v1_DeleteWebhookRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_chalk_server_v1_DeleteWebhookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_DeleteWebhookRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_chalk_server_v1_DeleteWebhookResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_chalk_server_v1_DeleteWebhookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_DeleteWebhookResponse_descriptor,
        new java.lang.String[] { "Webhook", });
    internal_static_chalk_server_v1_GetWebhookRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_chalk_server_v1_GetWebhookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_GetWebhookRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_chalk_server_v1_GetWebhookResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_chalk_server_v1_GetWebhookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_GetWebhookResponse_descriptor,
        new java.lang.String[] { "Webhook", });
    internal_static_chalk_server_v1_ListWebhooksRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_chalk_server_v1_ListWebhooksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_ListWebhooksRequest_descriptor,
        new java.lang.String[] { "EnvironmentId", });
    internal_static_chalk_server_v1_ListWebhooksResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_chalk_server_v1_ListWebhooksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chalk_server_v1_ListWebhooksResponse_descriptor,
        new java.lang.String[] { "Webhooks", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(ai.chalk.protos.chalk.auth.v1.PermissionsProto.permission);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    ai.chalk.protos.chalk.auth.v1.PermissionsProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
