// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/lsp/v1/lsp.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.lsp.v1;

/**
 * Protobuf type {@code chalk.lsp.v1.TextDocumentEdit}
 */
public final class TextDocumentEdit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chalk.lsp.v1.TextDocumentEdit)
    TextDocumentEditOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TextDocumentEdit.newBuilder() to construct.
  private TextDocumentEdit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TextDocumentEdit() {
    edits_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TextDocumentEdit();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.chalk.protos.chalk.lsp.v1.LspProto.internal_static_chalk_lsp_v1_TextDocumentEdit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.chalk.protos.chalk.lsp.v1.LspProto.internal_static_chalk_lsp_v1_TextDocumentEdit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit.class, ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit.Builder.class);
  }

  private int bitField0_;
  public static final int TEXT_DOCUMENT_FIELD_NUMBER = 1;
  private ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier textDocument_;
  /**
   * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
   * @return Whether the textDocument field is set.
   */
  @java.lang.Override
  public boolean hasTextDocument() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
   * @return The textDocument.
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier getTextDocument() {
    return textDocument_ == null ? ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.getDefaultInstance() : textDocument_;
  }
  /**
   * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifierOrBuilder getTextDocumentOrBuilder() {
    return textDocument_ == null ? ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.getDefaultInstance() : textDocument_;
  }

  public static final int EDITS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<ai.chalk.protos.chalk.lsp.v1.TextEdit> edits_;
  /**
   * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
   */
  @java.lang.Override
  public java.util.List<ai.chalk.protos.chalk.lsp.v1.TextEdit> getEditsList() {
    return edits_;
  }
  /**
   * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends ai.chalk.protos.chalk.lsp.v1.TextEditOrBuilder> 
      getEditsOrBuilderList() {
    return edits_;
  }
  /**
   * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
   */
  @java.lang.Override
  public int getEditsCount() {
    return edits_.size();
  }
  /**
   * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.lsp.v1.TextEdit getEdits(int index) {
    return edits_.get(index);
  }
  /**
   * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.lsp.v1.TextEditOrBuilder getEditsOrBuilder(
      int index) {
    return edits_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTextDocument());
    }
    for (int i = 0; i < edits_.size(); i++) {
      output.writeMessage(2, edits_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTextDocument());
    }
    for (int i = 0; i < edits_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, edits_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit)) {
      return super.equals(obj);
    }
    ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit other = (ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit) obj;

    if (hasTextDocument() != other.hasTextDocument()) return false;
    if (hasTextDocument()) {
      if (!getTextDocument()
          .equals(other.getTextDocument())) return false;
    }
    if (!getEditsList()
        .equals(other.getEditsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTextDocument()) {
      hash = (37 * hash) + TEXT_DOCUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getTextDocument().hashCode();
    }
    if (getEditsCount() > 0) {
      hash = (37 * hash) + EDITS_FIELD_NUMBER;
      hash = (53 * hash) + getEditsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chalk.lsp.v1.TextDocumentEdit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chalk.lsp.v1.TextDocumentEdit)
      ai.chalk.protos.chalk.lsp.v1.TextDocumentEditOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.chalk.protos.chalk.lsp.v1.LspProto.internal_static_chalk_lsp_v1_TextDocumentEdit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.chalk.protos.chalk.lsp.v1.LspProto.internal_static_chalk_lsp_v1_TextDocumentEdit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit.class, ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit.Builder.class);
    }

    // Construct using ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTextDocumentFieldBuilder();
        getEditsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      textDocument_ = null;
      if (textDocumentBuilder_ != null) {
        textDocumentBuilder_.dispose();
        textDocumentBuilder_ = null;
      }
      if (editsBuilder_ == null) {
        edits_ = java.util.Collections.emptyList();
      } else {
        edits_ = null;
        editsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.chalk.protos.chalk.lsp.v1.LspProto.internal_static_chalk_lsp_v1_TextDocumentEdit_descriptor;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit getDefaultInstanceForType() {
      return ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit.getDefaultInstance();
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit build() {
      ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit buildPartial() {
      ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit result = new ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit result) {
      if (editsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          edits_ = java.util.Collections.unmodifiableList(edits_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.edits_ = edits_;
      } else {
        result.edits_ = editsBuilder_.build();
      }
    }

    private void buildPartial0(ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.textDocument_ = textDocumentBuilder_ == null
            ? textDocument_
            : textDocumentBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit) {
        return mergeFrom((ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit other) {
      if (other == ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit.getDefaultInstance()) return this;
      if (other.hasTextDocument()) {
        mergeTextDocument(other.getTextDocument());
      }
      if (editsBuilder_ == null) {
        if (!other.edits_.isEmpty()) {
          if (edits_.isEmpty()) {
            edits_ = other.edits_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEditsIsMutable();
            edits_.addAll(other.edits_);
          }
          onChanged();
        }
      } else {
        if (!other.edits_.isEmpty()) {
          if (editsBuilder_.isEmpty()) {
            editsBuilder_.dispose();
            editsBuilder_ = null;
            edits_ = other.edits_;
            bitField0_ = (bitField0_ & ~0x00000002);
            editsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEditsFieldBuilder() : null;
          } else {
            editsBuilder_.addAllMessages(other.edits_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTextDocumentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              ai.chalk.protos.chalk.lsp.v1.TextEdit m =
                  input.readMessage(
                      ai.chalk.protos.chalk.lsp.v1.TextEdit.parser(),
                      extensionRegistry);
              if (editsBuilder_ == null) {
                ensureEditsIsMutable();
                edits_.add(m);
              } else {
                editsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier textDocument_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier, ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.Builder, ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifierOrBuilder> textDocumentBuilder_;
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     * @return Whether the textDocument field is set.
     */
    public boolean hasTextDocument() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     * @return The textDocument.
     */
    public ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier getTextDocument() {
      if (textDocumentBuilder_ == null) {
        return textDocument_ == null ? ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.getDefaultInstance() : textDocument_;
      } else {
        return textDocumentBuilder_.getMessage();
      }
    }
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     */
    public Builder setTextDocument(ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier value) {
      if (textDocumentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        textDocument_ = value;
      } else {
        textDocumentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     */
    public Builder setTextDocument(
        ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.Builder builderForValue) {
      if (textDocumentBuilder_ == null) {
        textDocument_ = builderForValue.build();
      } else {
        textDocumentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     */
    public Builder mergeTextDocument(ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier value) {
      if (textDocumentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          textDocument_ != null &&
          textDocument_ != ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.getDefaultInstance()) {
          getTextDocumentBuilder().mergeFrom(value);
        } else {
          textDocument_ = value;
        }
      } else {
        textDocumentBuilder_.mergeFrom(value);
      }
      if (textDocument_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     */
    public Builder clearTextDocument() {
      bitField0_ = (bitField0_ & ~0x00000001);
      textDocument_ = null;
      if (textDocumentBuilder_ != null) {
        textDocumentBuilder_.dispose();
        textDocumentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     */
    public ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.Builder getTextDocumentBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTextDocumentFieldBuilder().getBuilder();
    }
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     */
    public ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifierOrBuilder getTextDocumentOrBuilder() {
      if (textDocumentBuilder_ != null) {
        return textDocumentBuilder_.getMessageOrBuilder();
      } else {
        return textDocument_ == null ?
            ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.getDefaultInstance() : textDocument_;
      }
    }
    /**
     * <code>.chalk.lsp.v1.TextDocumentIdentifier text_document = 1 [json_name = "textDocument"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier, ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.Builder, ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifierOrBuilder> 
        getTextDocumentFieldBuilder() {
      if (textDocumentBuilder_ == null) {
        textDocumentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier, ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifier.Builder, ai.chalk.protos.chalk.lsp.v1.TextDocumentIdentifierOrBuilder>(
                getTextDocument(),
                getParentForChildren(),
                isClean());
        textDocument_ = null;
      }
      return textDocumentBuilder_;
    }

    private java.util.List<ai.chalk.protos.chalk.lsp.v1.TextEdit> edits_ =
      java.util.Collections.emptyList();
    private void ensureEditsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        edits_ = new java.util.ArrayList<ai.chalk.protos.chalk.lsp.v1.TextEdit>(edits_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.chalk.protos.chalk.lsp.v1.TextEdit, ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder, ai.chalk.protos.chalk.lsp.v1.TextEditOrBuilder> editsBuilder_;

    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public java.util.List<ai.chalk.protos.chalk.lsp.v1.TextEdit> getEditsList() {
      if (editsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(edits_);
      } else {
        return editsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public int getEditsCount() {
      if (editsBuilder_ == null) {
        return edits_.size();
      } else {
        return editsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public ai.chalk.protos.chalk.lsp.v1.TextEdit getEdits(int index) {
      if (editsBuilder_ == null) {
        return edits_.get(index);
      } else {
        return editsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder setEdits(
        int index, ai.chalk.protos.chalk.lsp.v1.TextEdit value) {
      if (editsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEditsIsMutable();
        edits_.set(index, value);
        onChanged();
      } else {
        editsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder setEdits(
        int index, ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder builderForValue) {
      if (editsBuilder_ == null) {
        ensureEditsIsMutable();
        edits_.set(index, builderForValue.build());
        onChanged();
      } else {
        editsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder addEdits(ai.chalk.protos.chalk.lsp.v1.TextEdit value) {
      if (editsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEditsIsMutable();
        edits_.add(value);
        onChanged();
      } else {
        editsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder addEdits(
        int index, ai.chalk.protos.chalk.lsp.v1.TextEdit value) {
      if (editsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEditsIsMutable();
        edits_.add(index, value);
        onChanged();
      } else {
        editsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder addEdits(
        ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder builderForValue) {
      if (editsBuilder_ == null) {
        ensureEditsIsMutable();
        edits_.add(builderForValue.build());
        onChanged();
      } else {
        editsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder addEdits(
        int index, ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder builderForValue) {
      if (editsBuilder_ == null) {
        ensureEditsIsMutable();
        edits_.add(index, builderForValue.build());
        onChanged();
      } else {
        editsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder addAllEdits(
        java.lang.Iterable<? extends ai.chalk.protos.chalk.lsp.v1.TextEdit> values) {
      if (editsBuilder_ == null) {
        ensureEditsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, edits_);
        onChanged();
      } else {
        editsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder clearEdits() {
      if (editsBuilder_ == null) {
        edits_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        editsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public Builder removeEdits(int index) {
      if (editsBuilder_ == null) {
        ensureEditsIsMutable();
        edits_.remove(index);
        onChanged();
      } else {
        editsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder getEditsBuilder(
        int index) {
      return getEditsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public ai.chalk.protos.chalk.lsp.v1.TextEditOrBuilder getEditsOrBuilder(
        int index) {
      if (editsBuilder_ == null) {
        return edits_.get(index);  } else {
        return editsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public java.util.List<? extends ai.chalk.protos.chalk.lsp.v1.TextEditOrBuilder> 
         getEditsOrBuilderList() {
      if (editsBuilder_ != null) {
        return editsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(edits_);
      }
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder addEditsBuilder() {
      return getEditsFieldBuilder().addBuilder(
          ai.chalk.protos.chalk.lsp.v1.TextEdit.getDefaultInstance());
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder addEditsBuilder(
        int index) {
      return getEditsFieldBuilder().addBuilder(
          index, ai.chalk.protos.chalk.lsp.v1.TextEdit.getDefaultInstance());
    }
    /**
     * <code>repeated .chalk.lsp.v1.TextEdit edits = 2 [json_name = "edits"];</code>
     */
    public java.util.List<ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder> 
         getEditsBuilderList() {
      return getEditsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.chalk.protos.chalk.lsp.v1.TextEdit, ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder, ai.chalk.protos.chalk.lsp.v1.TextEditOrBuilder> 
        getEditsFieldBuilder() {
      if (editsBuilder_ == null) {
        editsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ai.chalk.protos.chalk.lsp.v1.TextEdit, ai.chalk.protos.chalk.lsp.v1.TextEdit.Builder, ai.chalk.protos.chalk.lsp.v1.TextEditOrBuilder>(
                edits_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        edits_ = null;
      }
      return editsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chalk.lsp.v1.TextDocumentEdit)
  }

  // @@protoc_insertion_point(class_scope:chalk.lsp.v1.TextDocumentEdit)
  private static final ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit();
  }

  public static ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TextDocumentEdit>
      PARSER = new com.google.protobuf.AbstractParser<TextDocumentEdit>() {
    @java.lang.Override
    public TextDocumentEdit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TextDocumentEdit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TextDocumentEdit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.chalk.protos.chalk.lsp.v1.TextDocumentEdit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

