// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/graph/v1/graph.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.graph.v1;

/**
 * Protobuf enum {@code chalk.graph.v1.Finalizer}
 */
public enum Finalizer
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FINALIZER_UNSPECIFIED = 0;</code>
   */
  FINALIZER_UNSPECIFIED(0),
  /**
   * <code>FINALIZER_ONE_OR_NONE = 1;</code>
   */
  FINALIZER_ONE_OR_NONE(1),
  /**
   * <code>FINALIZER_ONE = 2;</code>
   */
  FINALIZER_ONE(2),
  /**
   * <code>FINALIZER_FIRST = 3;</code>
   */
  FINALIZER_FIRST(3),
  /**
   * <code>FINALIZER_ALL = 4;</code>
   */
  FINALIZER_ALL(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FINALIZER_UNSPECIFIED = 0;</code>
   */
  public static final int FINALIZER_UNSPECIFIED_VALUE = 0;
  /**
   * <code>FINALIZER_ONE_OR_NONE = 1;</code>
   */
  public static final int FINALIZER_ONE_OR_NONE_VALUE = 1;
  /**
   * <code>FINALIZER_ONE = 2;</code>
   */
  public static final int FINALIZER_ONE_VALUE = 2;
  /**
   * <code>FINALIZER_FIRST = 3;</code>
   */
  public static final int FINALIZER_FIRST_VALUE = 3;
  /**
   * <code>FINALIZER_ALL = 4;</code>
   */
  public static final int FINALIZER_ALL_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Finalizer valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Finalizer forNumber(int value) {
    switch (value) {
      case 0: return FINALIZER_UNSPECIFIED;
      case 1: return FINALIZER_ONE_OR_NONE;
      case 2: return FINALIZER_ONE;
      case 3: return FINALIZER_FIRST;
      case 4: return FINALIZER_ALL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Finalizer>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Finalizer> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Finalizer>() {
          public Finalizer findValueByNumber(int number) {
            return Finalizer.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ai.chalk.protos.chalk.graph.v1.GraphProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final Finalizer[] VALUES = values();

  public static Finalizer valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Finalizer(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:chalk.graph.v1.Finalizer)
}

