// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/graph/v1/sources.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.graph.v1;

public interface StreamSourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.graph.v1.StreamSource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chalk.graph.v1.KafkaSource kafka = 1 [json_name = "kafka"];</code>
   * @return Whether the kafka field is set.
   */
  boolean hasKafka();
  /**
   * <code>.chalk.graph.v1.KafkaSource kafka = 1 [json_name = "kafka"];</code>
   * @return The kafka.
   */
  ai.chalk.protos.chalk.graph.v1.KafkaSource getKafka();
  /**
   * <code>.chalk.graph.v1.KafkaSource kafka = 1 [json_name = "kafka"];</code>
   */
  ai.chalk.protos.chalk.graph.v1.KafkaSourceOrBuilder getKafkaOrBuilder();

  /**
   * <code>.chalk.graph.v1.KinesisSource kinesis = 2 [json_name = "kinesis"];</code>
   * @return Whether the kinesis field is set.
   */
  boolean hasKinesis();
  /**
   * <code>.chalk.graph.v1.KinesisSource kinesis = 2 [json_name = "kinesis"];</code>
   * @return The kinesis.
   */
  ai.chalk.protos.chalk.graph.v1.KinesisSource getKinesis();
  /**
   * <code>.chalk.graph.v1.KinesisSource kinesis = 2 [json_name = "kinesis"];</code>
   */
  ai.chalk.protos.chalk.graph.v1.KinesisSourceOrBuilder getKinesisOrBuilder();

  /**
   * <code>.chalk.graph.v1.PubSubSource pubsub = 3 [json_name = "pubsub"];</code>
   * @return Whether the pubsub field is set.
   */
  boolean hasPubsub();
  /**
   * <code>.chalk.graph.v1.PubSubSource pubsub = 3 [json_name = "pubsub"];</code>
   * @return The pubsub.
   */
  ai.chalk.protos.chalk.graph.v1.PubSubSource getPubsub();
  /**
   * <code>.chalk.graph.v1.PubSubSource pubsub = 3 [json_name = "pubsub"];</code>
   */
  ai.chalk.protos.chalk.graph.v1.PubSubSourceOrBuilder getPubsubOrBuilder();

  ai.chalk.protos.chalk.graph.v1.StreamSource.SourceCase getSourceCase();
}
