// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/common/v1/feature_values.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.common.v1;

@java.lang.Deprecated public interface GetFeatureValuesChartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.common.v1.GetFeatureValuesChartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chalk.common.v1.Chart chart = 1 [json_name = "chart"];</code>
   * @return Whether the chart field is set.
   */
  boolean hasChart();
  /**
   * <code>.chalk.common.v1.Chart chart = 1 [json_name = "chart"];</code>
   * @return The chart.
   */
  ai.chalk.protos.chalk.common.v1.Chart getChart();
  /**
   * <code>.chalk.common.v1.Chart chart = 1 [json_name = "chart"];</code>
   */
  ai.chalk.protos.chalk.common.v1.ChartOrBuilder getChartOrBuilder();
}
