// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/common/v1/online_query.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.common.v1;

public interface OnlineQueryMetadataInternalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.common.v1.OnlineQueryMetadataInternal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string json_plan = 1 [json_name = "jsonPlan"];</code>
   * @return Whether the jsonPlan field is set.
   */
  boolean hasJsonPlan();
  /**
   * <code>optional string json_plan = 1 [json_name = "jsonPlan"];</code>
   * @return The jsonPlan.
   */
  java.lang.String getJsonPlan();
  /**
   * <code>optional string json_plan = 1 [json_name = "jsonPlan"];</code>
   * @return The bytes for jsonPlan.
   */
  com.google.protobuf.ByteString
      getJsonPlanBytes();

  /**
   * <code>optional string serialized_plan = 2 [json_name = "serializedPlan"];</code>
   * @return Whether the serializedPlan field is set.
   */
  boolean hasSerializedPlan();
  /**
   * <code>optional string serialized_plan = 2 [json_name = "serializedPlan"];</code>
   * @return The serializedPlan.
   */
  java.lang.String getSerializedPlan();
  /**
   * <code>optional string serialized_plan = 2 [json_name = "serializedPlan"];</code>
   * @return The bytes for serializedPlan.
   */
  com.google.protobuf.ByteString
      getSerializedPlanBytes();

  /**
   * <code>optional string serialized_static_plan = 3 [json_name = "serializedStaticPlan"];</code>
   * @return Whether the serializedStaticPlan field is set.
   */
  boolean hasSerializedStaticPlan();
  /**
   * <code>optional string serialized_static_plan = 3 [json_name = "serializedStaticPlan"];</code>
   * @return The serializedStaticPlan.
   */
  java.lang.String getSerializedStaticPlan();
  /**
   * <code>optional string serialized_static_plan = 3 [json_name = "serializedStaticPlan"];</code>
   * @return The bytes for serializedStaticPlan.
   */
  com.google.protobuf.ByteString
      getSerializedStaticPlanBytes();

  /**
   * <code>optional string serialized_static_physical_plan = 4 [json_name = "serializedStaticPhysicalPlan"];</code>
   * @return Whether the serializedStaticPhysicalPlan field is set.
   */
  boolean hasSerializedStaticPhysicalPlan();
  /**
   * <code>optional string serialized_static_physical_plan = 4 [json_name = "serializedStaticPhysicalPlan"];</code>
   * @return The serializedStaticPhysicalPlan.
   */
  java.lang.String getSerializedStaticPhysicalPlan();
  /**
   * <code>optional string serialized_static_physical_plan = 4 [json_name = "serializedStaticPhysicalPlan"];</code>
   * @return The bytes for serializedStaticPhysicalPlan.
   */
  com.google.protobuf.ByteString
      getSerializedStaticPhysicalPlanBytes();

  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; planner_options = 5 [json_name = "plannerOptions"];</code>
   */
  int getPlannerOptionsCount();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; planner_options = 5 [json_name = "plannerOptions"];</code>
   */
  boolean containsPlannerOptions(
      java.lang.String key);
  /**
   * Use {@link #getPlannerOptionsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Value>
  getPlannerOptions();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; planner_options = 5 [json_name = "plannerOptions"];</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Value>
  getPlannerOptionsMap();
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; planner_options = 5 [json_name = "plannerOptions"];</code>
   */
  /* nullable */
com.google.protobuf.Value getPlannerOptionsOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.Value defaultValue);
  /**
   * <code>map&lt;string, .google.protobuf.Value&gt; planner_options = 5 [json_name = "plannerOptions"];</code>
   */
  com.google.protobuf.Value getPlannerOptionsOrThrow(
      java.lang.String key);

  /**
   * <code>optional bool plan_stages_stored = 6 [json_name = "planStagesStored"];</code>
   * @return Whether the planStagesStored field is set.
   */
  boolean hasPlanStagesStored();
  /**
   * <code>optional bool plan_stages_stored = 6 [json_name = "planStagesStored"];</code>
   * @return The planStagesStored.
   */
  boolean getPlanStagesStored();

  /**
   * <code>optional string performance_summary = 7 [json_name = "performanceSummary"];</code>
   * @return Whether the performanceSummary field is set.
   */
  boolean hasPerformanceSummary();
  /**
   * <code>optional string performance_summary = 7 [json_name = "performanceSummary"];</code>
   * @return The performanceSummary.
   */
  java.lang.String getPerformanceSummary();
  /**
   * <code>optional string performance_summary = 7 [json_name = "performanceSummary"];</code>
   * @return The bytes for performanceSummary.
   */
  com.google.protobuf.ByteString
      getPerformanceSummaryBytes();

  /**
   * <code>optional .chalk.common.v1.BusMessageIDs bus_message_ids = 8 [json_name = "busMessageIds"];</code>
   * @return Whether the busMessageIds field is set.
   */
  boolean hasBusMessageIds();
  /**
   * <code>optional .chalk.common.v1.BusMessageIDs bus_message_ids = 8 [json_name = "busMessageIds"];</code>
   * @return The busMessageIds.
   */
  ai.chalk.protos.chalk.common.v1.BusMessageIDs getBusMessageIds();
  /**
   * <code>optional .chalk.common.v1.BusMessageIDs bus_message_ids = 8 [json_name = "busMessageIds"];</code>
   */
  ai.chalk.protos.chalk.common.v1.BusMessageIDsOrBuilder getBusMessageIdsOrBuilder();

  /**
   * <code>repeated string value_tables = 9 [json_name = "valueTables"];</code>
   * @return A list containing the valueTables.
   */
  java.util.List<java.lang.String>
      getValueTablesList();
  /**
   * <code>repeated string value_tables = 9 [json_name = "valueTables"];</code>
   * @return The count of valueTables.
   */
  int getValueTablesCount();
  /**
   * <code>repeated string value_tables = 9 [json_name = "valueTables"];</code>
   * @param index The index of the element to return.
   * @return The valueTables at the given index.
   */
  java.lang.String getValueTables(int index);
  /**
   * <code>repeated string value_tables = 9 [json_name = "valueTables"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the valueTables at the given index.
   */
  com.google.protobuf.ByteString
      getValueTablesBytes(int index);
}
