// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/common/v1/query_log.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.common.v1;

public interface VersionedQueryNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.common.v1.VersionedQueryName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query_name = 1 [json_name = "queryName"];</code>
   * @return The queryName.
   */
  java.lang.String getQueryName();
  /**
   * <code>string query_name = 1 [json_name = "queryName"];</code>
   * @return The bytes for queryName.
   */
  com.google.protobuf.ByteString
      getQueryNameBytes();

  /**
   * <code>optional string query_name_version = 2 [json_name = "queryNameVersion"];</code>
   * @return Whether the queryNameVersion field is set.
   */
  boolean hasQueryNameVersion();
  /**
   * <code>optional string query_name_version = 2 [json_name = "queryNameVersion"];</code>
   * @return The queryNameVersion.
   */
  java.lang.String getQueryNameVersion();
  /**
   * <code>optional string query_name_version = 2 [json_name = "queryNameVersion"];</code>
   * @return The bytes for queryNameVersion.
   */
  com.google.protobuf.ByteString
      getQueryNameVersionBytes();
}
