// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/expression/v1/expression.proto

// Protobuf Java Version: 3.25.3
package ai.chalk.protos.chalk.expression.v1;

public interface GetIndexedFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.expression.v1.GetIndexedField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chalk.expression.v1.LogicalExprNode expr = 1 [json_name = "expr"];</code>
   * @return Whether the expr field is set.
   */
  boolean hasExpr();
  /**
   * <code>.chalk.expression.v1.LogicalExprNode expr = 1 [json_name = "expr"];</code>
   * @return The expr.
   */
  ai.chalk.protos.chalk.expression.v1.LogicalExprNode getExpr();
  /**
   * <code>.chalk.expression.v1.LogicalExprNode expr = 1 [json_name = "expr"];</code>
   */
  ai.chalk.protos.chalk.expression.v1.LogicalExprNodeOrBuilder getExprOrBuilder();

  /**
   * <code>.chalk.expression.v1.NamedStructField named_struct_field = 2 [json_name = "namedStructField"];</code>
   * @return Whether the namedStructField field is set.
   */
  boolean hasNamedStructField();
  /**
   * <code>.chalk.expression.v1.NamedStructField named_struct_field = 2 [json_name = "namedStructField"];</code>
   * @return The namedStructField.
   */
  ai.chalk.protos.chalk.expression.v1.NamedStructField getNamedStructField();
  /**
   * <code>.chalk.expression.v1.NamedStructField named_struct_field = 2 [json_name = "namedStructField"];</code>
   */
  ai.chalk.protos.chalk.expression.v1.NamedStructFieldOrBuilder getNamedStructFieldOrBuilder();

  /**
   * <code>.chalk.expression.v1.ListIndex list_index = 3 [json_name = "listIndex"];</code>
   * @return Whether the listIndex field is set.
   */
  boolean hasListIndex();
  /**
   * <code>.chalk.expression.v1.ListIndex list_index = 3 [json_name = "listIndex"];</code>
   * @return The listIndex.
   */
  ai.chalk.protos.chalk.expression.v1.ListIndex getListIndex();
  /**
   * <code>.chalk.expression.v1.ListIndex list_index = 3 [json_name = "listIndex"];</code>
   */
  ai.chalk.protos.chalk.expression.v1.ListIndexOrBuilder getListIndexOrBuilder();

  /**
   * <code>.chalk.expression.v1.ListRange list_range = 4 [json_name = "listRange"];</code>
   * @return Whether the listRange field is set.
   */
  boolean hasListRange();
  /**
   * <code>.chalk.expression.v1.ListRange list_range = 4 [json_name = "listRange"];</code>
   * @return The listRange.
   */
  ai.chalk.protos.chalk.expression.v1.ListRange getListRange();
  /**
   * <code>.chalk.expression.v1.ListRange list_range = 4 [json_name = "listRange"];</code>
   */
  ai.chalk.protos.chalk.expression.v1.ListRangeOrBuilder getListRangeOrBuilder();

  ai.chalk.protos.chalk.expression.v1.GetIndexedField.FieldCase getFieldCase();
}
