// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/aggregate/v1/service.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.aggregate.v1;

public interface CronAggregateBackfillWithLatestRunOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chalk.aggregate.v1.CronAggregateBackfillWithLatestRun)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
   * @return Whether the cronAggregateBackfill field is set.
   */
  boolean hasCronAggregateBackfill();
  /**
   * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
   * @return The cronAggregateBackfill.
   */
  ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill getCronAggregateBackfill();
  /**
   * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
   */
  ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillOrBuilder getCronAggregateBackfillOrBuilder();

  /**
   * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
   * @return Whether the latestJob field is set.
   */
  boolean hasLatestJob();
  /**
   * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
   * @return The latestJob.
   */
  ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob getLatestJob();
  /**
   * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
   */
  ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJobOrBuilder getLatestJobOrBuilder();
}
