// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/aggregate/v1/service.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.aggregate.v1;

/**
 * Protobuf type {@code chalk.aggregate.v1.CronAggregateBackfillWithLatestRun}
 */
public final class CronAggregateBackfillWithLatestRun extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chalk.aggregate.v1.CronAggregateBackfillWithLatestRun)
    CronAggregateBackfillWithLatestRunOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CronAggregateBackfillWithLatestRun.newBuilder() to construct.
  private CronAggregateBackfillWithLatestRun(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CronAggregateBackfillWithLatestRun() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CronAggregateBackfillWithLatestRun();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.chalk.protos.chalk.aggregate.v1.ServiceProto.internal_static_chalk_aggregate_v1_CronAggregateBackfillWithLatestRun_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.chalk.protos.chalk.aggregate.v1.ServiceProto.internal_static_chalk_aggregate_v1_CronAggregateBackfillWithLatestRun_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun.class, ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun.Builder.class);
  }

  private int bitField0_;
  public static final int CRON_AGGREGATE_BACKFILL_FIELD_NUMBER = 1;
  private ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill cronAggregateBackfill_;
  /**
   * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
   * @return Whether the cronAggregateBackfill field is set.
   */
  @java.lang.Override
  public boolean hasCronAggregateBackfill() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
   * @return The cronAggregateBackfill.
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill getCronAggregateBackfill() {
    return cronAggregateBackfill_ == null ? ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.getDefaultInstance() : cronAggregateBackfill_;
  }
  /**
   * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillOrBuilder getCronAggregateBackfillOrBuilder() {
    return cronAggregateBackfill_ == null ? ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.getDefaultInstance() : cronAggregateBackfill_;
  }

  public static final int LATEST_JOB_FIELD_NUMBER = 2;
  private ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob latestJob_;
  /**
   * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
   * @return Whether the latestJob field is set.
   */
  @java.lang.Override
  public boolean hasLatestJob() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
   * @return The latestJob.
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob getLatestJob() {
    return latestJob_ == null ? ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.getDefaultInstance() : latestJob_;
  }
  /**
   * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
   */
  @java.lang.Override
  public ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJobOrBuilder getLatestJobOrBuilder() {
    return latestJob_ == null ? ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.getDefaultInstance() : latestJob_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCronAggregateBackfill());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getLatestJob());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCronAggregateBackfill());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getLatestJob());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun)) {
      return super.equals(obj);
    }
    ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun other = (ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun) obj;

    if (hasCronAggregateBackfill() != other.hasCronAggregateBackfill()) return false;
    if (hasCronAggregateBackfill()) {
      if (!getCronAggregateBackfill()
          .equals(other.getCronAggregateBackfill())) return false;
    }
    if (hasLatestJob() != other.hasLatestJob()) return false;
    if (hasLatestJob()) {
      if (!getLatestJob()
          .equals(other.getLatestJob())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCronAggregateBackfill()) {
      hash = (37 * hash) + CRON_AGGREGATE_BACKFILL_FIELD_NUMBER;
      hash = (53 * hash) + getCronAggregateBackfill().hashCode();
    }
    if (hasLatestJob()) {
      hash = (37 * hash) + LATEST_JOB_FIELD_NUMBER;
      hash = (53 * hash) + getLatestJob().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chalk.aggregate.v1.CronAggregateBackfillWithLatestRun}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chalk.aggregate.v1.CronAggregateBackfillWithLatestRun)
      ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRunOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.chalk.protos.chalk.aggregate.v1.ServiceProto.internal_static_chalk_aggregate_v1_CronAggregateBackfillWithLatestRun_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.chalk.protos.chalk.aggregate.v1.ServiceProto.internal_static_chalk_aggregate_v1_CronAggregateBackfillWithLatestRun_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun.class, ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun.Builder.class);
    }

    // Construct using ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCronAggregateBackfillFieldBuilder();
        getLatestJobFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cronAggregateBackfill_ = null;
      if (cronAggregateBackfillBuilder_ != null) {
        cronAggregateBackfillBuilder_.dispose();
        cronAggregateBackfillBuilder_ = null;
      }
      latestJob_ = null;
      if (latestJobBuilder_ != null) {
        latestJobBuilder_.dispose();
        latestJobBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.chalk.protos.chalk.aggregate.v1.ServiceProto.internal_static_chalk_aggregate_v1_CronAggregateBackfillWithLatestRun_descriptor;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun getDefaultInstanceForType() {
      return ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun.getDefaultInstance();
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun build() {
      ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun buildPartial() {
      ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun result = new ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cronAggregateBackfill_ = cronAggregateBackfillBuilder_ == null
            ? cronAggregateBackfill_
            : cronAggregateBackfillBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.latestJob_ = latestJobBuilder_ == null
            ? latestJob_
            : latestJobBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun) {
        return mergeFrom((ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun other) {
      if (other == ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun.getDefaultInstance()) return this;
      if (other.hasCronAggregateBackfill()) {
        mergeCronAggregateBackfill(other.getCronAggregateBackfill());
      }
      if (other.hasLatestJob()) {
        mergeLatestJob(other.getLatestJob());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCronAggregateBackfillFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getLatestJobFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill cronAggregateBackfill_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill, ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.Builder, ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillOrBuilder> cronAggregateBackfillBuilder_;
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     * @return Whether the cronAggregateBackfill field is set.
     */
    public boolean hasCronAggregateBackfill() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     * @return The cronAggregateBackfill.
     */
    public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill getCronAggregateBackfill() {
      if (cronAggregateBackfillBuilder_ == null) {
        return cronAggregateBackfill_ == null ? ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.getDefaultInstance() : cronAggregateBackfill_;
      } else {
        return cronAggregateBackfillBuilder_.getMessage();
      }
    }
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     */
    public Builder setCronAggregateBackfill(ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill value) {
      if (cronAggregateBackfillBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cronAggregateBackfill_ = value;
      } else {
        cronAggregateBackfillBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     */
    public Builder setCronAggregateBackfill(
        ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.Builder builderForValue) {
      if (cronAggregateBackfillBuilder_ == null) {
        cronAggregateBackfill_ = builderForValue.build();
      } else {
        cronAggregateBackfillBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     */
    public Builder mergeCronAggregateBackfill(ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill value) {
      if (cronAggregateBackfillBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          cronAggregateBackfill_ != null &&
          cronAggregateBackfill_ != ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.getDefaultInstance()) {
          getCronAggregateBackfillBuilder().mergeFrom(value);
        } else {
          cronAggregateBackfill_ = value;
        }
      } else {
        cronAggregateBackfillBuilder_.mergeFrom(value);
      }
      if (cronAggregateBackfill_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     */
    public Builder clearCronAggregateBackfill() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cronAggregateBackfill_ = null;
      if (cronAggregateBackfillBuilder_ != null) {
        cronAggregateBackfillBuilder_.dispose();
        cronAggregateBackfillBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     */
    public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.Builder getCronAggregateBackfillBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCronAggregateBackfillFieldBuilder().getBuilder();
    }
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     */
    public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillOrBuilder getCronAggregateBackfillOrBuilder() {
      if (cronAggregateBackfillBuilder_ != null) {
        return cronAggregateBackfillBuilder_.getMessageOrBuilder();
      } else {
        return cronAggregateBackfill_ == null ?
            ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.getDefaultInstance() : cronAggregateBackfill_;
      }
    }
    /**
     * <code>.chalk.aggregate.v1.CronAggregateBackfill cron_aggregate_backfill = 1 [json_name = "cronAggregateBackfill"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill, ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.Builder, ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillOrBuilder> 
        getCronAggregateBackfillFieldBuilder() {
      if (cronAggregateBackfillBuilder_ == null) {
        cronAggregateBackfillBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill, ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfill.Builder, ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillOrBuilder>(
                getCronAggregateBackfill(),
                getParentForChildren(),
                isClean());
        cronAggregateBackfill_ = null;
      }
      return cronAggregateBackfillBuilder_;
    }

    private ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob latestJob_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob, ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.Builder, ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJobOrBuilder> latestJobBuilder_;
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     * @return Whether the latestJob field is set.
     */
    public boolean hasLatestJob() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     * @return The latestJob.
     */
    public ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob getLatestJob() {
      if (latestJobBuilder_ == null) {
        return latestJob_ == null ? ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.getDefaultInstance() : latestJob_;
      } else {
        return latestJobBuilder_.getMessage();
      }
    }
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     */
    public Builder setLatestJob(ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob value) {
      if (latestJobBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        latestJob_ = value;
      } else {
        latestJobBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     */
    public Builder setLatestJob(
        ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.Builder builderForValue) {
      if (latestJobBuilder_ == null) {
        latestJob_ = builderForValue.build();
      } else {
        latestJobBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     */
    public Builder mergeLatestJob(ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob value) {
      if (latestJobBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          latestJob_ != null &&
          latestJob_ != ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.getDefaultInstance()) {
          getLatestJobBuilder().mergeFrom(value);
        } else {
          latestJob_ = value;
        }
      } else {
        latestJobBuilder_.mergeFrom(value);
      }
      if (latestJob_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     */
    public Builder clearLatestJob() {
      bitField0_ = (bitField0_ & ~0x00000002);
      latestJob_ = null;
      if (latestJobBuilder_ != null) {
        latestJobBuilder_.dispose();
        latestJobBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     */
    public ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.Builder getLatestJobBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getLatestJobFieldBuilder().getBuilder();
    }
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     */
    public ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJobOrBuilder getLatestJobOrBuilder() {
      if (latestJobBuilder_ != null) {
        return latestJobBuilder_.getMessageOrBuilder();
      } else {
        return latestJob_ == null ?
            ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.getDefaultInstance() : latestJob_;
      }
    }
    /**
     * <code>.chalk.aggregate.v1.AggregateBackfillJob latest_job = 2 [json_name = "latestJob"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob, ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.Builder, ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJobOrBuilder> 
        getLatestJobFieldBuilder() {
      if (latestJobBuilder_ == null) {
        latestJobBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob, ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJob.Builder, ai.chalk.protos.chalk.aggregate.v1.AggregateBackfillJobOrBuilder>(
                getLatestJob(),
                getParentForChildren(),
                isClean());
        latestJob_ = null;
      }
      return latestJobBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chalk.aggregate.v1.CronAggregateBackfillWithLatestRun)
  }

  // @@protoc_insertion_point(class_scope:chalk.aggregate.v1.CronAggregateBackfillWithLatestRun)
  private static final ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun();
  }

  public static ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CronAggregateBackfillWithLatestRun>
      PARSER = new com.google.protobuf.AbstractParser<CronAggregateBackfillWithLatestRun>() {
    @java.lang.Override
    public CronAggregateBackfillWithLatestRun parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CronAggregateBackfillWithLatestRun> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CronAggregateBackfillWithLatestRun> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.chalk.protos.chalk.aggregate.v1.CronAggregateBackfillWithLatestRun getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

