// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chalk/metrics/v4/metrics.proto

// Protobuf Java Version: 3.25.1
package ai.chalk.protos.chalk.metrics.v4;

/**
 * Protobuf enum {@code chalk.metrics.v4.MetricNamespace}
 */
public enum MetricNamespace
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>METRIC_NAMESPACE_UNSPECIFIED = 0;</code>
   */
  METRIC_NAMESPACE_UNSPECIFIED(0),
  /**
   * <code>METRIC_NAMESPACE_FEATURE = 1;</code>
   */
  METRIC_NAMESPACE_FEATURE(1),
  /**
   * <code>METRIC_NAMESPACE_SYSTEM = 2;</code>
   */
  METRIC_NAMESPACE_SYSTEM(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>METRIC_NAMESPACE_UNSPECIFIED = 0;</code>
   */
  public static final int METRIC_NAMESPACE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>METRIC_NAMESPACE_FEATURE = 1;</code>
   */
  public static final int METRIC_NAMESPACE_FEATURE_VALUE = 1;
  /**
   * <code>METRIC_NAMESPACE_SYSTEM = 2;</code>
   */
  public static final int METRIC_NAMESPACE_SYSTEM_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MetricNamespace valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MetricNamespace forNumber(int value) {
    switch (value) {
      case 0: return METRIC_NAMESPACE_UNSPECIFIED;
      case 1: return METRIC_NAMESPACE_FEATURE;
      case 2: return METRIC_NAMESPACE_SYSTEM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MetricNamespace>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MetricNamespace> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MetricNamespace>() {
          public MetricNamespace findValueByNumber(int number) {
            return MetricNamespace.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ai.chalk.protos.chalk.metrics.v4.MetricsProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final MetricNamespace[] VALUES = values();

  public static MetricNamespace valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MetricNamespace(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:chalk.metrics.v4.MetricNamespace)
}

