name: Auto approve labels
on:
  pull_request:
    types: [ labeled ]
  workflow_dispatch: {}

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: hmarr/auto-approve-action@v4
        if: contains(github.event.pull_request.labels.*.name, 'skip-approval')
        with:
          review-message: "Auto approved automated PR due to label"
      - name: Force merge pull request
        if: contains(github.event.pull_request.labels.*.name, 'force-merge')
        run: |
            # Use squash merge
            gh pr --repo chalk-ai/chalk-private merge ${{ github.event.pull_request.number }} --admin --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.CI_SERVICES_GITHUB_TOKEN }}