name: Publish to Maven Central

on:
  workflow_dispatch:

  release:
    types:
      - "published"

jobs:
  build:
    name: "Release and Publish"
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - uses: actions/checkout@v4

      - name: Extract Version from GitHub Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update README.md with new version
        run: |
          # Replace Gradle version line
          sed -i "s|implementation 'ai.chalk:chalk-java:[0-9.]*'|implementation 'ai.chalk:chalk-java:${VERSION}'|" README.md

          # Replace Maven version line
          sed -i "s|<version>[0-9.]*</version>|<version>${VERSION}</version>|" README.md
        env:
          VERSION: ${{ env.VERSION }}

      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push if changed
        if: env.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README with version from gradle.properties"
          git push

      - name: Run Gradle Release (Version Bumping & Tagging)
        run: ./gradlew release -Prelease.releaseVersion=$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}

      - name: Publish to Sonatype
        run: ./gradlew publish closeAndReleaseSonatypeStagingRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
