name: Publish to Maven Central

on:
  pull_request:
    types:
      - "labeled"

jobs:
  build:
    name: "Publish to Maven Central"
    if: github.event_name == 'release' || github.event.label.name == 'release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: gradle
          distribution: 'oracle'

      - name: Publish to Sonatype
        run: ./gradlew publish closeAndReleaseSonatypeStagingRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
