name: Publish to Sonatype

on:
  workflow_dispatch:

  release:
    types:
      - "published"

jobs:
  build:
    name: "Publish to Sonatype"
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: actions/checkout@v4

      - name: Publish to Sonatype
        run: ./gradlew publish
