name: Run tests

#  public class ConfigEnvVars {
#  /**
#  * Specifies the URL that all requests from ChalkClient will be sent to.
#  */
#  public static String apiServerKey = "CHALK_API_SERVER";
#
#  /**
#  * Used for authentication (obtaining an access token).
#  */
#  public static String clientIdKey = "CHALK_CLIENT_ID";
#
#  /**
#  * Used for authentication (obtaining an access token).
#  */
#  public static String clientSecretKey = "CHALK_CLIENT_SECRET";
#
#  /**
#  * This is the identifier that distinguishes between different
#  * environments in your Chalk project.
#  */
#  public static String environmentIdKey = "CHALK_ACTIVE_ENVIRONMENT";
#}

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
        env:
          CHALK_API_SERVER: ${{ secrets.CHALK_API_SERVER }}
          CHALK_CLIENT_ID: ${{ secrets.CHALK_CLIENT_ID }}
          CHALK_CLIENT_SECRET: ${{ secrets.CHALK_CLIENT_SECRET }}
          CHALK_ACTIVE_ENVIRONMENT: ${{ secrets.CHALK_ACTIVE_ENVIRONMENT }}
