name: Run tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'gradle'
#
#      - name: Run check style
#        uses: nikitasavinov/checkstyle-action@master
#        with:
#          reporter: 'github-pr-check'
#          tool_name: 'testtool'

      - name: Run tests
        run: ./gradlew test --stacktrace
        env:
          CHALK_API_SERVER: ${{ secrets.CHALK_API_SERVER }}
          CHALK_CLIENT_ID: ${{ secrets.CHALK_CLIENT_ID }}
          CHALK_CLIENT_SECRET: ${{ secrets.CHALK_CLIENT_SECRET }}
          CHALK_ACTIVE_ENVIRONMENT: ${{ secrets.CHALK_ACTIVE_ENVIRONMENT }}
          STAGING_QA_ENV_ID: ${{ secrets.STAGING_QA_ENV_ID }}
          STAGING_DEV_ENV_ID: ${{ secrets.STAGING_DEV_ENV_ID }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: chalk-java
