name: Run tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Run tests
        run: ./gradlew test
        env:
          CHALK_API_SERVER: ${{ secrets.CHALK_API_SERVER }}
          CHALK_CLIENT_ID: ${{ secrets.CHALK_CLIENT_ID }}
          CHALK_CLIENT_SECRET: ${{ secrets.CHALK_CLIENT_SECRET }}
          CHALK_ACTIVE_ENVIRONMENT: ${{ secrets.CHALK_ACTIVE_ENVIRONMENT }}
